from .product import product
from .product import product_product
from .temporality import temporality
from .brand import brand
from .wishlist import wishlist
from .res_users import res_users
from .promotions import purchase_promotion
from .promotions import products_without_charge
from .promotions import promotion_type
from .promotions import plan_goals
from .purchase import purchase
from .purchase import purchase_order_line
from .stock import stock_picking
from .stock import stock_quant
from .stock import stock_move
from .stock import stock_location
from .stock import stock_move_line
from .res_partner import res_partner
from .pos import pos_config_date
from .pos import pos_config
from .pos import pos_session
#from .pos import pos_order
from .account import account_move
from .account import account_move_line
from .calendar import calendar_event
from .sale import sale_order
from .pricelist import pricelist_item